Service events

diff --git a/example-service b/example-service
--- a/example-service
+++ b/example-service
@@ -10,17 +10,30 @@ run-script() {
   local action="$1" # Action
 
   while true; do
-    echo "Running action '${action}'"
+    echo "@@@ Running action '${action}'"
     echo foo
     echo bar >&2
 
     [ "$action" = "run" ] && return 0
     sleep 5
+    [ "$action" = "debug" ] && exit 25
   done
+}
+
+before-start() {
+  local action="$1" # Action
+
+  echo "* Starting with $action"
+}
+
+after-finish() {
+  local action="$1" # Action
+  local serviceExitCode=$2 # Service exit code
+
+  echo "* Finish with $action. Exit code: $serviceExitCode"
 }
 
 action="$1"
 serviceName="Example Service"
-command="run-script" # Using "custom function"
 
-serviceMenu "$action" "$serviceName" "$command" "$workDir"
+serviceMenu "$action" "$serviceName" run-script "$workDir" before-start after-finish
